#!/bin/sh

# help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Supermicro IPMIView"
    echo "Usage:"
    echo "  ipmiview -n,--noscale"
    echo "-n or --noscale will disable double DPI scaling of the window."
    exit 0
fi

# must run as normal user
if [ "$(id -u)" = 0 ]; then
    echo 'This script must be run as a normal user, not root!' >&2
    exit 1
fi

UI_SCALE="$1"

if [ "$UI_SCALE" = "--noscale" ] || [ "$UI_SCALE" = "-n" ]; then
    ARG_SCALE="1"
else
    ARG_SCALE="2.5"
fi

# ipmiview will save all config files to this directory
WORK_DIR="$HOME/.ipmiview"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR" || exit 1
java -Dsun.java2d.uiScale="$ARG_SCALE" \
    -jar /usr/local/share/ipmiview/orig/IPMIView20.jar
